### ISSUE TITLE
Stworzenie podstawowego projektu (dla wszystkich)

### ISSUE THREAD

**Issue by pawelbojnowski** [pawelbojnowski/SZ_podania#14]
1. Dodanie połączenia z bazą danych (bazę H2 proponuję na początek) http://spring.io/guides/gs/accessing-data-jpa/

2. Dodanie MVC do projektu (dodanie przykładowego widoku, potrzebnych plików css/js/jQuery Bootstrapa, AngularaJS, itp) http://spring.io/guides/gs/serving-web-content/

3. Poszukać sposobu na stworzenie/użycie szablonu (Tak żeby nie kopiować postarzającej się zawartość)

**Comment by my4n** [comment]
Heh, tylko jedna osoba może być przypisana?

**Comment by Stosiu** [comment]
Wygląda na to że tak :(
